### ISSUE TITLE
前端面试题集锦

### ISSUE THREAD

**Issue by yugasun** [yugasun/yugasun.github.io#1]
# 前端面试题集锦

### 1.HTML5新增了哪些内容或API，使用过哪些
localStorage/sessionStorage: setItem/getItem, 最大容量~5M
canvas, video, audio,

### 2.input和textarea的区别
* input为单行文本框，textarea为多行文本框
* input的值通过value属性指定和修改，textarea的值居于 textarea标签之间
* textarea中可以存储换行字符
* textarea可以手动更改高宽（没有这事style.resize为none）,input 无法手动更改高宽

### 3.用一个div模拟textarea的实现
使用HTML5新属性 `contenteditable`，如下：
```html
<div class="textarea" contenteditable="true"></div>
```

```css
/* 注意IE6不识别max-height，所以需要借助js来实现 */
.textarea{
    width: 400px;
    min-height: 20px;
    max-height: 300px;
    overflow: scroll;
    overflow-x: hidden;
    overflow-y: auto;
    _height: 20px;
    _overflow-y: visible;
    outline: 0;
}
```

### 1.左右布局：左边定宽、右边自适应，不少于3种方法

```html
<div class="wrapper">
   <div class="left">ddd</div>
   <div class="right">ddd</div>
</div>
```

```css
/* 1. 方法1 */
.wrapper{
  width: 400px;
  height: 200px;
}
.left{
  width: 50px;
  height: 100%;
  background-color: red;
  float: left;
}
.right {
  width: auto;
  height: 100%;
  padding-left: 50px;
  background-color: green;
}

/* 方法2 */
.wrapper{
  width: 400px;
  height: 200px;
}
.left{
  width: 50px;
  height: 100%;
  background-color: red;
  float: left;
}
.right {
  width: auto;
  height: 100%;
  margin-left: 50px;
  background-color: green;
}

/* 方法3 */
.wrapper {
  width: 400px;
  height: 200px;
  overflow: hidden;
}

.left {
  float: left;
  width: 50px;
  height: 100%;
  background-color: red;
  margin-right: -100%;
}

.right {
  float: left;
  width: 100%;
  height: 100%;
}

.right_content {
  margin-left: 50px;
  background-color: green;
}
```

### 2.CSS3用过哪些新特性
* transform: translate,rotate,scale.... 变换
* transition: all .3s ease; 指定变化缓动
* animation: 
  1. animation-name: Specifies the name of the @keyframes at-rule describing the animation's keyframes.
  2. animation-duration: Configures the length of time that an animation should take to complete one cycle
  3. animation-timing-function: linear,ease,ease-in,ease-out,ease-in-out,cubic-bezier(n,n,n,n)
  4. animation-delay: Configures the delay between the time the element is loaded and the beginning of the animation sequence
  5. animation-iteration-count: Configures the number of times the animation should repeat; you can specify infinite to repeat the animation indefinitely.
  6. animation-direction: Configures whether or not the animation should alternate direction on each run through the sequence or reset to the start point and repeat itself.
  7. animation-play-state: Lets you pause and resume the animation sequence.
  8. animation-fill-mode: Configures what values are applied by the animation before and after it is executing.
* `@keyframe animationName{from/to{},0%{}100%{}}` 帧动画
* `@media screen and (max-width: 300px) not (aspect-ratio	: 1/2){}`
* `@font-face{}`

### 3.BFC、IFC

FC的含义就是Fomatting Context。它是CSS2.1规范中的一个概念。它是页面中的一块渲染区域，并且有一套渲染规则，它决定了其子元素将如何定位，以及和其他元素的关系和相互作用。BFC和IFC都是常见的FC。

* BFC - Block Fomatting Context 块级格式化上下文
    1. 内部的盒子会在垂直方向，一个个地放置；
    2. 盒子垂直方向的距离由margin决定，属于同一个BFC的两个相邻Box的上下margin会发生重叠；
    3. 每个元素的左边，与包含的盒子的左边相接触，即使存在浮动也是如此；
    4. BFC的区域不会与float重叠；
    5. BFC就是页面上的一个隔离的独立容器，容器里面的子元素不会影响到外面的元素，反之也如此；
    6. 计算BFC的高度时，浮动元素也参与计算。

* IFC - Inline Formatting Context 行内格式化上下文

### 4.对栅格的理解

一个栅格系统由四部分组成： container、row、column、gutter.
以规则的网格阵列来指导和规范网页中的版面布局以及信息分布
栅格系统优点：

* 提高生产力，通过在网格的划分，元素更容易堆放而且在跨浏览器上面具有一致性，使我们可以专心的注意布局而不是兼容上。
* 具有灵活性，无论是什么样的布局，都可以拆分到粒度为一个网格的大小。
* 支持响应式设计，栅格系统本身能很好的和响应式设计结合在一起，或者说，我们的栅格系统是基于响应式设计的。

### 5.（水平）居中有哪些实现方式

```html
<div class="parent">
    <div class="block"></div>
</div>
```

```css
/* 方法1 */
.block{
    margin: 0 auto;
}
/* 方法2 */
.block{
    position: absolute;
    left: 50%;
    transform: translateX(-50%);
}
/* 方法3 */
.parent {
    text-align: center;
}
.block{
    width: 50px;
    height: 50px;
    background-color: red;
    display: inline-block;
}
```

### 6. 1像素边框问题

* 方法1: 根据 `window.devicePixelRatio` 的值 `>= 2` 来设置全局 `border-width: 0.5px`

```css
.hairlines div {
    border-width: 0.5px;
}
```

```javascript
     window.onload = function () {
      if (window.devicePixelRatio && window.devicePixelRatio >= 2) {
        var testElem = document.createElement('div');
        testElem.style.border = '.5px solid transparent';
        document.body.appendChild(testElem);
        if (testElem.offsetHeight == 1) {
          document.querySelector('html').classList.add('hairlines');
        }
        document.body.removeChild(testElem);
      }
    }
```

* 方法2

```css
 .border-image-1px {
    border-width: 1px 0px;
    border-image: url("图片是2px高，上部的1px颜色为透明，下部的1px使用视觉规定的border的颜色") 2 0 stretch;
}
```

* 方法3

```css
.background-gradient-1px {
    background: linear-gradient(180deg, black, black 50%, transparent 50%) top left / 100% 1px no-repeat,
 linear-gradient(90deg, transparent, transparent 50%, black 50%) top right / 1px 100% no-repeat,
 linear-gradient(0, black, black 50%, transparent 50%) bottom right / 100% 1px no-repeat,
 linear-gradient(-90deg, transparent, transparent 50%, black 50%) bottom left / 1px 100% no-repeat;
}
```

* 方法4

```css
.box-shadow-1px {
    box-shadow: inset 0px 0px 0.5px #000000;
}
```

### 1.图片懒加载

图片延迟加载的原理就是先不设置img的src属性，等合适的时机（比如滚动、滑动等）再把图片真实url放到img的src属性上。
过多的图片会严重影响网页的加载速度，移动网络下的流量消耗巨大，延迟加载几乎是标配。

总结为4步：

* 把真正的图片地址存在自定义属性上
* 当图片满足加载条件的时候，创建临时的img对象校验图片地址的正确性；
* 地址正确，进入onload事件，把正确地址赋值src；不正确，进入onerr;
* 注意性能优化：释放没用的临时图片对象

### 2.实现页面加载进度条
![](http://o6sbyl9mg.bkt.clouddn.com/14967466834383.jpg)

* **方法1**：因此我们需要通过html代码逐行加载的特性，在整页代码的若干个跳跃行数中设置节点，进行大概的模糊进度反馈来实现进度加载的效果。大致意思是：页面每加载到指定区域，则返回(n)%的进度结果，通过设置多个节点，来达到一步一步显示加载进度的目的
* **方法2**：借助第三方插件如：[nprogress](https://github.com/rstacruz/nprogress/) 

  ```javascript
  (function (window, NProgress) {
     NProgress.start();
     window.onload = function () {
       NProgress.done();
     }
  })(window, NProgress);
  ```

### 3.事件委托
通常在监听列表点击事件时，如果每个列表项单独添加监听事件，这个页面会额外多出很多事件监听，资源浪费，可以将列表项代理到他们的父级节点 `ul` 上，当点击ul时，通过判断e.target的 `tagName === 'LI'` 来执行相关操作。如下：
```html
<ul>
    <li>1</li>
    <li>2</li>
    <li>3</li>
</ul>
```

```javascript
(function () {
    document.querySelector('ul').addEventListener('click',    function(e){
       let target = e.target;
       if(target.tagName === 'LI'){
         console.log(target.innerHTML);
       }
     })
})();
```

### 4.实现extend函数
```javascript
function extend(target, source) {
    for (var key in source) {
        if ((typeof source[key]) === 'object') {
            var temp = (Object.prototype.toString.call(source[key]).slice(8, -1) === 'Array' ? [] : {});
            target[key] = extend(temp, source[key]);
        } else {
         target[key] = source[key];
        }
    }
    return target;
}
```

### 5.为什么会有跨域的问题以及解决方式
问题1：

* 浏览器基于安全限制的同源策略（同协议，同域名，同端口），提出同源策略的目的是出于安全性考虑，它能够阻止来自恶意网站的脚本通过其他网站的DOM获取其他网站的信息。可以避免CSRF和XSS攻击。主要限制的是JavaScript跨站请求数据。

问题2：

* JSONP 通过回调函数来进行跨域获取最终的值；
* CORS 通过服务端设置 HEADER 头来设置允许的域名来进行跨域，现代浏览器常用；(设置 `Access-Control-Allow-Origin` 的值为 `*`或对应的域名)
* IFrame 来进行跨域，通信可以用 postMessage；
* 服务端代理来进行跨域，跨域的服务器不受控制

### 6.jsonp原理、postMessage原理

1. jsonp原理：首先在客户端注册一个callback, 然后把callback的名字传给服务器。此时，服务器先生成 json 数据。然后以 javascript 语法的方式，生成一个function , function 名字就是传递上来的参数 jsonp.最后将 json 数据直接以入参的方式，放置到 function 中，这样就生成了一段 js 语法的文档，返回给客户端。客户端浏览器，解析script标签，并执行返回的 javascript 文档，此时数据作为参数，传入到了客户端预先定义好的 callback 函数里.（动态执行回调函数）

```javascript
function jsonpCallback(result) {  
   //alert(result);  
   for(var i in result) {  
       alert(i+":"+result[i]);//循环输出a:1,b:2,etc.  
   }  
}  
var JSONP=document.createElement("script");  
JSONP.type="text/javascript";  
JSONP.src="http://crossdomain.com/services.php?callback=jsonpCallback";  
document.getElementsByTagName("head")[0].appendChild(JSONP);  
```

2. postMessage原理：

```html
 <!-- 通过 iframe 嵌入子页面 --> 
	 <iframe src="http://jhssdemo.duapp.com/demo/h5_postmessage/win.html" id="otherWin"></iframe> 
	 <input type="text" id="message">
	 <input type="button" value="Send to child.com" id="sendMessage" /> 
```

发送消息：

```javascript
document.getElementById('sendMessage').onclick = function(){
    document.getElementById("otherWin").contentWindow.postMessage(document.getElementById("message").value, "http://jhssdemo.duapp.com/"); 
}
```

接受消息：

```javascript
window.addEventListener('message',function(e){
    console.log("Got a message!");
    console.log("\nMessage: " + e.data);
    console.log("\nOrigin: " + e.origin);
	 console.log("Source: " + e.source);
}, false);
```

### 7.实现拖拽功能，比如把5个兄弟节点中的最后一个节点拖拽到节点1和节点2之间

[Dragger](https://github.com/yugasun/dragger)

### 8.动画：setTimeout何时执行，requestAnimationFrame的优点

**对于setTimeout**:

* setTimeout 不会阻塞进程; 它只会让其包裹的代码延迟指定的时间执行。

* 当线程闲下来的时候，才会执行任务队列池中等待的异步任务；即：setTimeout 会等到线程空闲才会执行

**对于requestAnimationFrame**：

* requestAnimationFrame会把每一帧中的所有DOM操作集中起来，在一次重绘或回流中就完成，并且重绘或回流的时间间隔紧紧跟随浏览器的刷新频率

* 在隐藏或不可见的元素中，requestAnimationFrame将不会进行重绘或回流，这当然就意味着更少的CPU、GPU和内存使用量

* requestAnimationFrame是由浏览器专门为动画提供的API，在运行时浏览器会自动优化方法的调用，并且如果页面不是激活状态下的话，动画会自动暂停，有效节省了CPU开销
    
### 9.手写parseInt的实现：要求简单一些，把字符串型的数字转化为真正的数字即可，但不能使用JS原生的字符串转数字的API，比如Number()

```javascript
function parseInt(str){
    str = str.toString();
    var numReg = /^\d+/g;
    var arr = numReg.exec(str);
    return arr !== null ? arr[0] * 1 : NaN;
}
```

### 10.编写分页器组件的时候，为了减少服务端查询次数，点击“下一页”怎样能确保还有数据可以加载（请求数据不会为空）？

无论前端做分页还是后台做分页，我们都能拿到数据总量，根据数据总量和当前页显示的条数，求出分页总数count，所以，点击下一页，主要看页码是否超出总数count，如果超出，则不能再有点击事件，因为数据已经为空；

### 11.ES6新增了哪些特性，使用过哪些，也有当场看代码说输出结果的

1. 类型：let, const, Set, Map, class, 字符串模板
2. 操作： 
    * 数组操作： sArray.find, Array.findIndex, Array.fill
    * 函数：rest参数 ..., :: bind this
    * 对象：浅拷贝 Object.assign, Object.keys(), Object,values(), 扩展运算符...,
3. 新增对象： Promise
    * 对象的状态不受外界影响，Promise对象代表一个异步操作，有三种状态：Pending（进行中）、Resolved（已完成，又称 Fulfilled）和Rejected（已失败）
    * 一旦状态改变，就不会再变，任何时候都可以得到这个结果。
4. 箭头函数
5. generators
 

### 12.JS模块化的实践

* 单例模式开发： 可以把模块写成一个对象，所有的模块成员都放到这个对象里面。进行模块化开发最简单的方式

    ```javascript
    var app = {
        a: 1,
        func: function(){
            console.log(this.a);
        }
    };
    ```
    
* 立即执行函数+单例模式的写法

    ```javascript
    var utils=(function(){
        return {
            mod1:()=>{.....},
            mod2:()=>{.....}    
        }
    })();
    ```
    
* Javascript模块规范共有两种：CommonJS和AMD
    
    - commonJS规范：主要适用服务器端，通过exports导出，通过require导入；
    - AMD规范：主要有两个js库，requirejs和sea.js

### 14.promise的实现原理，进一步会问async、await是否使用过

promise的实现原理

* 对象的状态不受外界影响，Promise对象代表一个异步操作，有三种状态：Pending（进行中）、Resolved（已完成，又称 Fulfilled）和Rejected（已失败）
* 一旦状态改变，就不会再变，任何时候都可以得到这个结果。

```
function resolveAfter2Seconds(x){
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            resolve(x);
        }, 2000);
    })
}
var add1 = async (x) => {
    var a = resolveAfter2Seconds(20);
    var b = resolveAfter2Seconds(30);
    return x + await a + await b;
}
add1(10).then(v => {
  console.log(v);  // prints 60 after 2 seconds.
});
var add2 = async (x) => {
    var a = await resolveAfter2Seconds(20);
    var b = await resolveAfter2Seconds(30);
    return x + a + b;
};
add2(10).then(v => {
    console.log(v); // prints 60 after 4 seconds
})
```

### 15.实现gulp的功能

？？？

### 16.使用前端框架（angular/vue/react）带来哪些好处，相对于使用jQuery

使用Vuejs:

1. 组件化的开发，增强模块组件可复用性
2. 完善的项目工程化
3. 视图模型化，绑定数据，修改data，视图也相应变化
4. Virtual Dom 减少DOM操作

### 17.vue双向数据绑定的实现

```javascript
function defineReactive(obj, key, value) {
    var dep = new Dep()
    Object.defineProperty(obj, key, {
        enumerable: true,
        configurable: true,
        get: function reactiveGetter() {
            if (Dep.target) {
                // 收集依赖
                dep.depend()
            }
            return value
        },
        set: function reactiveSetter(newVal) {
            if (value === newVal) {
                return
            } else {
                value = newVal
                // 通知watcher，重新计算，更新视图
                dep.notify()
            }
        }
    })
}
```

### 18.单页应用，如何实现其路由功能

[SPARouter](https://github.com/yugasun/SPARouter)

### 项目中使用过哪些优化方法

| 优化方向	| 优化手段
| ------- | ----------------------
| 请求数量	| 合并脚本和样式表，CSS Sprites，拆分初始化负载，划分主域
| 请求带宽	| 开启GZip，精简JavaScript，移除重复脚本，图像优化
| 缓存利用	| 使用CDN，使用外部JavaScript和CSS，添加Expires头，减少 DNS查找，配置ETag，使AjaX可缓存
| 页面结构	| 将样式表放在顶部，将脚本放在底部，尽早刷新文档的输出
| 代码校验	| 避免CSS表达式，避免重定向

### 2.输入一个URL，Enter之后发生了什么

1. 浏览器解析URL，再DNS解析
2. 浏览器与网站建立TCP连接（三次握手）
3. 请求和传输数据
4. 浏览器渲染页面

### 3.（承上）页面的渲染过程

1. HTML代码转化成DOM
2. CSS代码转化成CSSOM （CSS Object Model）
3. 结合DOM和CSSOM, 生成一颗渲染树（包含每个节点的视觉信息）
4. 生成布局（layout）,即将所有渲染树的所有节点进行平面合成
5. 将布局绘制（paint）到屏幕上

![](http://o6sbyl9mg.bkt.clouddn.com/14979427181813.jpg)

#### 提高性能的九个技巧

有一些技巧，可以降低浏览器重新渲染的频率和成本。

1. 是上一节说到的，DOM 的多个读操作（或多个写操作），应该放在一起。不要两个读操作之间，加入一个写操作。
2. 如果某个样式是通过重排得到的，那么最好缓存结果。避免下一次用到的时候，浏览器又要重排。
3. 不要一条条地改变样式，而要通过改变class，或者csstext属性，一次性地改变样式。

    ```javascript
    // bad
    var left = 10;
    var top = 10;
    el.style.left = left + "px";
    el.style.top  = top  + "px";
    
    // good 
    el.className += " theclassname";
    
    // good
    el.style.cssText += "; left: " + left + "px; top: " + top + "px;";
    ```

4. 尽量使用离线DOM，而不是真实的网面DOM，来改变元素样式。比如，操作Document Fragment对象，完成后再把这个对象加入DOM。再比如，使用 cloneNode() 方法，在克隆的节点上进行操作，然后再用克隆的节点替换原始节点。
5. 先将元素设为display: none（需要1次重排和重绘），然后对这个节点进行100次操作，最后再恢复显示（需要1次重排和重绘）。这样一来，你就用两次重新渲染，取代了可能高达100次的重新渲染。
6. position属性为absolute或fixed的元素，重排的开销会比较小，因为不用考虑它对其他元素的影响。
7. 只在必要的时候，才将元素的display属性为可见，因为不可见的元素不影响重排和重绘。另外，visibility : hidden的元素只对重绘有影响，不影响重排。
8. 使用虚拟DOM的脚本库，比如React等。
9. 使用 window.requestAnimationFrame()、window.requestIdleCallback() 这两个方法调节重新渲染（详见后文）

### 4.优化中会提到缓存的问题，问：静态资源或者接口等如何做缓存优化

**1. 静态资源缓存优化**

* 静态资源缓存机制：以文件内容的hash值为依据生产新文件的非覆盖式发布策略是解决静态资源缓存更新最有效的手段

**2. 接口缓存优化**

* 接口合并

### 5.页面DOM节点太多，会出现什么问题？如何优化？

页面渲染卡顿，速度慢。
减少DOM节点

## 项目经历

项目中用到了某项技术，高级工程师的要求是：不仅会用，更要知道其原理。对自己的提醒：项目中用到的技术，不能说完全掌握其原理吧，但大致的实现还是有必要了解一下的。

你在项目中做的最出彩的一个地方
碰到过什么样的困难，怎么解决的
（如果你是这个项目的负责人），任务怎么分配的，有没有关注过团队成员的成长问题
前端安全问题：CSRF和XSS
